version: 0.2

phases:
  pre_build:
    commands:
      - echo "Downloading application dependencies..."
      - mvn clean install
  build:
    commands:
      - echo Entered the build phase...
      - mvn test # Ejecuta tus pruebas
      - mvn surefire-report:report # Genera el informe de pruebas
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - negocio/target/littlefriends1.jar
    - '**/*'
  base-directory: target/surefire-reports
  discard-paths: yes