version: 0.2

phases:
  pre_build:
    commands:
      - echo "Downloading application dependencies..."
      - mvn clean install
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - negocio/target/littlefriends1.jar
  discard-paths: yes